"use client";
/* eslint-disable @next/next/no-img-element -- owner asset paths are runtime-managed and optimized during upload. */
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import MediaUploader from "@/components/admin/MediaUploader";
import SmartLinkPicker, { SmartLinkEditingProvider } from "@/components/admin/SmartLinkPicker";
import { BlockVisualStyleEditor, HeroPlaybackEditor, VisualStyleStudio } from "@/components/admin/VisualStyleStudio";
import PageBuilderRenderer from "@/components/page-builder/PageBuilderRenderer";
import { createSection, duplicateSection, newBuilderId, resolveMobileMediaLayout, resolveSectionPresentation, type PageBuilderSection, type PageDraft, type PageMobileMediaLayout, type PagePresentationPreset, type PageRecord, type PageSectionType, type PageStore } from "@/lib/pageBuilder";
import { normalizeYouTubeVideoId } from "@/lib/youtubeMedia";
import { localImageMedia, youtubeMedia, type MediaAsset } from "@/lib/media";
import { resolveCmsLink, type CmsLinkProduct, type PublishedCmsPage } from "@/lib/cmsLinks";
import type { AssetRecord } from "@/lib/assets";
import { resolveWebsiteVisualStyle, type WebsiteVisualStyle } from "@/lib/pageBuilderVisualStyle";

const sectionChoices = [
  ["hero","主視覺","適合活動開場與主要訊息"],["mediaText","圖文介紹","照片／影片搭配文字"],["gallery","圖片影片展示","展示多張照片或影片"],["products","商品推薦","選擇要推薦的咖啡作品"],["features","賣點特色","整理活動或服務重點"],["text","文字內容","文章、說明、故事"],["cta","行動區","放置聯絡、購買或其他按鈕"],
] as const;
const sectionLabel = Object.fromEntries(sectionChoices.map(([key,label])=>[key,label]));
const statusLabel = { draft:"草稿", published:"已發布", unpublished:"未發布" } as const;
const presentationChoices: Record<PageSectionType, Array<[PagePresentationPreset,string,string,string]>> = {
  hero: [["hero-cinematic","電影滿版","活動主視覺、影片與季節發布","full"],["hero-editorial","精品左右","品牌介紹與圖文敘事","split"],["hero-campaign","活動主視覺","中秋、節慶與新品活動","campaign"],["hero-minimal","編輯式標題","故事、專題與咖啡哲學","minimal"],["hero-media-first","媒體主導","強照片或影片素材","media"]],
  mediaText: [["story-left","圖左・文字右","經典精品圖文","split"],["story-right","文字左・圖右","反向編輯式構圖","reverse"],["story-stacked","堆疊故事","大圖後接閱讀內容","stack"],["story-immersive","沉浸媒體","寬幅媒體與精簡說明","full"],["story-offset","錯位編輯","雜誌式非對稱構圖","offset"]],
  gallery: [["gallery-grid","編輯網格","整齊且有節奏的圖片網格","grid"],["gallery-feature","主圖＋輔圖","一張主視覺帶領其餘素材","feature"],["gallery-rail","橫向故事軸","適合多張媒體與手機瀏覽","rail"],["gallery-filmstrip","電影膠卷","連續、有節奏的寬幅展示","film"],["gallery-editorial","編輯式畫廊","受控的不對稱版面","editorial"]],
  products: [["products-featured","精選三款","主打商品的精品卡片","feature"],["products-rail","作品橫軸","多款作品的橫向瀏覽","rail"],["products-campaign","活動選品","適合節慶與限定組合","campaign"],["products-compact","精簡作品列","較短頁面的緊湊展示","compact"]],
  features: [["features-numbered","編號敘事","工藝與流程的順序故事","number"],["features-statement","主張＋細節","一個核心主張帶領內容","statement"],["features-three","三點故事","三個重點的平衡構圖","three"],["features-luxury","精品事實","安靜、無圖示的品牌資訊","luxury"]],
  cta: [["cta-editorial","編輯式收尾","明亮而有餘韻的行動區","editorial"],["cta-dark","深色電影收尾","強烈但克制的轉換區","dark"],["cta-compact","精簡行動","短頁面與單一行動","compact"],["cta-campaign","活動收尾","節慶與限定活動的結尾","campaign"]],
  text: [["text-editorial","閱讀文章","舒適的長文閱讀尺度","reading"],["text-statement","品牌宣言","短句與核心觀點","statement"]],
};

function move<T>(items:T[], index:number, direction:number) { const target=index+direction; if (target<0||target>=items.length) return items; const next=[...items]; [next[index],next[target]]=[next[target],next[index]]; return next; }
function Visibility({ enabled, label="顯示此內容", onChange }:{enabled:boolean;label?:string;onChange:(value:boolean)=>void}) { return <div className="owner-visibility-control"><span>{label}</span><div role="group" aria-label={label}><button type="button" className={enabled?"is-selected":""} aria-pressed={enabled} onClick={()=>onChange(true)}>✓ 顯示</button><button type="button" className={!enabled?"is-selected":""} aria-pressed={!enabled} onClick={()=>onChange(false)}>隱藏</button></div><b>{enabled?"顯示中":"已隱藏"}</b></div>; }

export default function PageBuilderManager({ pageId }:{pageId:string}) {
  const [store,setStore]=useState<PageStore|null>(null); const [page,setPage]=useState<PageRecord|null>(null); const [products,setProducts]=useState<CmsLinkProduct[]>([]); const [pages,setPages]=useState<PublishedCmsPage[]>([]); const [assets,setAssets]=useState<AssetRecord[]>([]); const [message,setMessage]=useState(""); const [chooser,setChooser]=useState(false); const [saving,setSaving]=useState(false); const [savingVisualStyle,setSavingVisualStyle]=useState(false); const [baseline,setBaseline]=useState(""); const [visualStyle,setVisualStyle]=useState<WebsiteVisualStyle>(()=>resolveWebsiteVisualStyle()); const [visualStyleBaseline,setVisualStyleBaseline]=useState(""); const [previewDevice,setPreviewDevice]=useState<"desktop"|"mobile">("desktop"); const [openSectionId,setOpenSectionId]=useState<string|null>(null);
  const [activeAction,setActiveAction]=useState<"save"|"publish"|"unpublish"|null>(null);
  const [completedAction,setCompletedAction]=useState<"save"|"publish"|null>(null);
  const [toast,setToast]=useState<{tone:"success"|"error";title:string;detail:string}|null>(null);
  const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>{void fetch("/api/admin/pages",{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);const loadedStore=data.store as PageStore;const found=loadedStore.pages.find(item=>item.id===pageId);if(!found)throw new Error("找不到頁面。");const loadedStyle=resolveWebsiteVisualStyle(loadedStore.visualStyle);setStore(loadedStore);setPage(found);setBaseline(JSON.stringify(found.draft));setVisualStyle(loadedStyle);setVisualStyleBaseline(JSON.stringify(loadedStyle));setProducts(data.products);setPages(data.publishedPages);setAssets(data.assets||[]);setOpenSectionId(found.draft.sections[0]?.id||null);}).catch(error=>setMessage(error.message));},[pageId]);
  const dirty=Boolean(page&&baseline&&JSON.stringify(page.draft)!==baseline);
  const visualStyleDirty=Boolean(visualStyleBaseline&&JSON.stringify(visualStyle)!==visualStyleBaseline);
  const anyDirty=dirty||visualStyleDirty;
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(!anyDirty)return;event.preventDefault();event.returnValue="";};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[anyDirty]);
  useEffect(()=>()=>{if(toastTimer.current)clearTimeout(toastTimer.current);},[]);
  function showToast(next:{tone:"success"|"error";title:string;detail:string}){setToast(next);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(null),4500);}
  function setDraft(updater:(draft:PageDraft)=>PageDraft){setPage(current=>current?{...current,draft:updater(current.draft)}:current);}
  async function save(operation:"save"|"publish"|"unpublish"="save") {
    if(!page||!store)return false;
    const scrollPosition=window.scrollY;
    setSaving(true);setActiveAction(operation);setCompletedAction(null);setMessage(operation==="publish"?"發布中…":operation==="unpublish"?"取消發布中…":"儲存中…");
    try {
      const response=await fetch(`/api/admin/pages/${page.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:store.version,operation,draft:page.draft,...(operation==="publish"?{visualStyle}: {})})});
      const data=await response.json();
      if(!response.ok)throw new Error(data.error||"更新失敗，請重新嘗試。");
      const savedStyle=data.visualStyle?resolveWebsiteVisualStyle(data.visualStyle):visualStyle;
      setPage(data.page);setBaseline(JSON.stringify(data.page.draft));setStore({...store,version:data.version,visualStyle:savedStyle,pages:store.pages.map(item=>item.id===data.page.id?data.page:item)});setPages(data.publishedPages||[]);
      if(data.visualStyle){setVisualStyle(savedStyle);setVisualStyleBaseline(JSON.stringify(savedStyle));}
      const nextMessage=operation==="publish"?"頁面已發布，頁面連結已同步更新。":operation==="unpublish"?"頁面已取消發布；草稿與媒體均已保留。":"草稿已安全儲存；公開頁面未被變更。";
      setMessage(nextMessage);
      if(operation==="publish"){setCompletedAction("publish");showToast({tone:"success",title:"✓ 網頁已更新發布",detail:"正式網站已套用最新內容"});}
      if(operation==="save"){setCompletedAction("save");showToast({tone:"success",title:"✓ 草稿已儲存",detail:"公開頁面沒有變更"});}
      requestAnimationFrame(()=>window.scrollTo({top:scrollPosition,left:0}));
      return true;
    } catch(error) {
      const detail=error instanceof Error?error.message:"更新失敗，請重新嘗試。";
      setMessage(detail);showToast({tone:"error",title:"⚠ 更新失敗",detail:"目前內容尚未發布，請重新嘗試"});return false;
    } finally {setSaving(false);setActiveAction(null);}
  }
  async function saveVisualStyle(){if(!page||!store)return;setSavingVisualStyle(true);setMessage("儲存網站視覺設定中…");const response=await fetch(`/api/admin/pages/${page.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:store.version,operation:"saveVisualStyle",visualStyle})});const data=await response.json();setSavingVisualStyle(false);if(!response.ok){setMessage(data.error);return;}const saved=resolveWebsiteVisualStyle(data.visualStyle);setVisualStyle(saved);setVisualStyleBaseline(JSON.stringify(saved));setStore({...store,version:data.version,visualStyle:saved});setMessage("網站視覺設定已儲存；頁面草稿與發布內容未被變更。");}
  async function preview(){if(await save("save"))window.open(`/admin/pages/${pageId}/preview`,"_blank","noopener,noreferrer");}
  if(!page||!store)return <p className="cms-feedback">{message||"載入頁面中…"}</p>;
  const publishedDestination=resolveCmsLink({type:"page",target:page.id},{pages});
  const publicHref=page.status==="published"&&Boolean(page.publishedSnapshot)&&publishedDestination.valid?publishedDestination.href:undefined;
  const updateSection=(index:number,next:PageBuilderSection)=>setDraft(draft=>({...draft,sections:draft.sections.map((item,i)=>i===index?next:item)}));
  const addSection=(type:typeof sectionChoices[number][0])=>{setDraft(draft=>({...draft,sections:[...draft.sections,createSection(type)]}));setChooser(false);};
  const publishedMatchesDraft=page.status==="published"&&Boolean(page.publishedSnapshot)&&JSON.stringify(page.draft)===JSON.stringify(page.publishedSnapshot);
  const saveLabel=activeAction==="save"?"儲存中…":completedAction==="save"&&!dirty?"✓ 已儲存":"儲存草稿";
  const publishLabel=activeAction==="publish"?"發布中…":publishedMatchesDraft&&!visualStyleDirty?"✓ 已發布":page.status==="published"?"更新發布":"發布頁面";
  return <SmartLinkEditingProvider><section className="page-admin-shell page-editor-shell"><header className="page-editor-heading page-editor-toolbar"><div><div className="page-editor-status-line"><span className={`owner-status status-${page.status}`}>{statusLabel[page.status]}</span><span className={`page-dirty-state ${anyDirty?"is-dirty":"is-saved"}`}>{anyDirty?"尚未儲存":"所有變更已儲存"}</span></div><h1>{page.draft.title}</h1><small>公開網址由系統管理・{page.draft.sections.length} 個區塊</small></div><div><button className="cms-secondary-button" type="button" onClick={preview} disabled={saving}>預覽草稿</button>{publicHref?<Link className="cms-secondary-button page-public-link" href={publicHref} target="_blank" rel="noreferrer">查看正式頁 ↗</Link>:null}<button className="cms-secondary-button" type="button" onClick={()=>save("save")} disabled={saving||!dirty}>{saveLabel}</button><button className="cms-primary-button" type="button" onClick={()=>save("publish")} disabled={saving}>{publishLabel}</button></div></header>
    {message?<p className="cms-feedback" role="status">{message}</p>:null}
    <div className="page-settings-card"><h2>頁面基本資料</h2><label>頁面名稱<input value={page.draft.title} maxLength={120} onChange={event=>setDraft(d=>({...d,title:event.target.value}))}/></label><details className="page-seo-settings"><summary>SEO 與搜尋結果設定</summary><div className="cms-grid two"><label>SEO 標題<input value={page.draft.seoTitle} maxLength={70} placeholder="留白時使用頁面名稱" onChange={event=>setDraft(d=>({...d,seoTitle:event.target.value}))}/></label><label className="span-two">SEO 說明<textarea value={page.draft.seoDescription} maxLength={180} onChange={event=>setDraft(d=>({...d,seoDescription:event.target.value}))}/></label></div></details>{page.status==="published"?<div className="page-secondary-publish-action"><span>要暫停公開頁面？草稿與媒體不會刪除。</span><button className="cms-danger-button" type="button" onClick={()=>confirm("取消發布後，公開頁面將立即停止顯示。內容不會刪除。")&&save("unpublish")} disabled={saving}>取消發布</button></div>:null}</div>
    <VisualStyleStudio value={visualStyle} sections={page.draft.sections} dirty={visualStyleDirty} saving={savingVisualStyle} onChange={setVisualStyle} onSave={saveVisualStyle}/>
    <details className="page-live-preview"><summary>頁面即時預覽</summary><div className="visual-device-switch"><button type="button" className={previewDevice==="desktop"?"is-selected":""} onClick={()=>setPreviewDevice("desktop")}>▰ 桌機</button><button type="button" className={previewDevice==="mobile"?"is-selected":""} onClick={()=>setPreviewDevice("mobile")}>▯ 手機</button></div><p>下方直接使用正式頁面的共用呈現方式；調整後立即更新，但不會自動儲存或發布。</p><div className={`page-live-preview-frame is-${previewDevice}`}><PageBuilderRenderer page={page.draft} products={products} registry={{products,pages}} visualStyle={visualStyle}/></div></details>
    <header className="page-content-heading"><div><p className="eyebrow dark">頁面編排</p><h2>頁面內容</h2></div><button className="cms-primary-button" type="button" onClick={()=>setChooser(true)}>＋新增區塊</button></header>
    {chooser?<div className="section-chooser"><header><h2>想加入什麼內容？</h2><button type="button" onClick={()=>setChooser(false)} aria-label="關閉">×</button></header><div>{sectionChoices.map(([key,label,description])=><button type="button" key={key} onClick={()=>addSection(key)}><strong>{label}</strong><span>{description}</span></button>)}</div></div>:null}
    <div className="page-section-list">{page.draft.sections.map((section,index)=><SectionEditor key={section.id} section={section} index={index} products={products} pages={pages} assets={assets} websiteStyle={visualStyle} expanded={openSectionId===section.id} onToggle={()=>setOpenSectionId(current=>current===section.id?null:section.id)} onAssetAdded={asset=>setAssets(current=>[asset,...current])} onChange={next=>updateSection(index,next)} onMove={direction=>setDraft(d=>({...d,sections:move(d.sections,index,direction)}))} onDuplicate={()=>setDraft(d=>({...d,sections:[...d.sections.slice(0,index+1),duplicateSection(section),...d.sections.slice(index+1)]}))} onRemove={()=>confirm(`確定移除「${sectionLabel[section.type]||"不支援的"}」區塊？`)&&setDraft(d=>({...d,sections:d.sections.filter((_,i)=>i!==index)}))} first={index===0} last={index===page.draft.sections.length-1}/>)}</div>
    {!page.draft.sections.length?<div className="page-admin-empty"><strong>這個頁面目前沒有內容</strong><span>按「＋新增區塊」選擇第一個品牌區塊。</span></div>:null}
    {toast?<div className={`owner-action-toast is-${toast.tone}`} role="status" aria-live="polite"><div><strong>{toast.title}</strong><span>{toast.detail}</span></div><button type="button" onClick={()=>setToast(null)} aria-label="關閉通知">×</button></div>:null}
  </section></SmartLinkEditingProvider>;
}

function SectionEditor({section,index,products,pages,assets,websiteStyle,expanded,onToggle,onAssetAdded,onChange,onMove,onDuplicate,onRemove,first,last}:{section:PageBuilderSection;index:number;products:CmsLinkProduct[];pages:PublishedCmsPage[];assets:AssetRecord[];websiteStyle:WebsiteVisualStyle;expanded:boolean;onToggle:()=>void;onAssetAdded:(asset:AssetRecord)=>void;onChange:(value:PageBuilderSection)=>void;onMove:(direction:number)=>void;onDuplicate:()=>void;onRemove:()=>void;first:boolean;last:boolean}) {
  const [youtubeUrl,setYoutubeUrl]=useState(""); const [pane,setPane]=useState<"content"|"media"|"buttons"|"layout"|"style"|"motion">("content"); const update=<K extends keyof PageBuilderSection>(key:K,value:PageBuilderSection[K])=>onChange({...section,[key]:value});
  if(!sectionLabel[section.type])return <article className="owner-surface is-hidden"><strong>這個區塊目前無法編輯</strong><p>正式頁面會安全略過；請移除或交由網站維護人員處理。</p><details><summary>查看技術資訊</summary><code>{String(section.type)}</code></details><button className="cms-danger-button" type="button" onClick={onRemove}>移除不支援區塊</button></article>;
  const addMedia=(media:MediaAsset)=>update("media",[...section.media,{id:newBuilderId("media"),enabled:true,media,alt:""}]);
  const addYoutube=()=>{try{const id=normalizeYouTubeVideoId(youtubeUrl);addMedia(youtubeMedia(id,youtubeUrl));setYoutubeUrl("");}catch{alert("請輸入有效的 YouTube 影片網址。");}};
  const supportsMedia=section.type==="hero"||section.type==="mediaText"||section.type==="gallery";
  const supportsButtons=section.type!=="gallery"&&section.type!=="products";
  const manualTitleWrap=(section.visualStyle?.headingWrap||(section.type==="hero"?websiteStyle.headingWrap:websiteStyle.secondaryHeadingWrap))==="manual";
  return <article className={`page-section-editor owner-surface ${section.enabled?"is-visible":"is-hidden"} ${expanded?"is-expanded":"is-collapsed"}`}><header className="page-section-summary"><button type="button" className="page-section-summary-main" onClick={onToggle} aria-expanded={expanded}><small>{String(index+1).padStart(2,"0")}</small><span><b>{sectionLabel[section.type]}</b><em>{section.title.trim()||section.eyebrow.trim()||"尚未輸入標題"}</em></span><span className="page-section-counts">{section.media.length?`${section.media.length} 個媒體`:"無媒體"}{section.ctas.length?`・${section.ctas.length} 個按鈕`:""}</span><span className="owner-status">{section.enabled?"顯示中":"已隱藏"}</span><strong>{expanded?"收合":"編輯"}</strong></button><Visibility enabled={section.enabled} label="顯示此區塊" onChange={value=>update("enabled",value)}/></header>
    {expanded?<><nav className="page-section-tabs" aria-label="區塊設定分類"><button type="button" className={pane==="content"?"is-active":""} onClick={()=>setPane("content")}>內容</button>{supportsMedia?<button type="button" className={pane==="media"?"is-active":""} onClick={()=>setPane("media")}>媒體</button>:null}{supportsButtons?<button type="button" className={pane==="buttons"?"is-active":""} onClick={()=>setPane("buttons")}>按鈕</button>:null}<button type="button" className={pane==="layout"?"is-active":""} onClick={()=>setPane("layout")}>版面</button><button type="button" className={pane==="style"?"is-active":""} onClick={()=>setPane("style")}>文字與色彩</button><button type="button" className={pane==="motion"?"is-active":""} onClick={()=>setPane("motion")}>動畫</button></nav>
    <div className="page-section-workspace">
      {pane==="content"?<><div className="cms-grid two"><label>小標<input value={section.eyebrow} maxLength={100} onChange={event=>update("eyebrow",event.target.value)}/></label><label>標題{manualTitleWrap?<textarea rows={2} value={section.title} maxLength={180} placeholder="按 Enter 決定換行位置" onChange={event=>update("title",event.target.value)}/>:<input value={section.title} maxLength={180} onChange={event=>update("title",event.target.value)}/>}</label>{section.type==="hero"?<label className="span-two">第二行標題<input value={section.headlineLine2||""} maxLength={180} onChange={event=>update("headlineLine2",event.target.value)}/></label>:null}<label className="span-two">內容（可自然換行）<textarea value={section.body} maxLength={5000} onChange={event=>update("body",event.target.value)}/></label></div>{section.type==="features"?<FeatureEditor section={section} update={update}/>:null}{section.type==="products"?<ProductEditor section={section} products={products} update={update}/>:null}</>:null}
      {pane==="media"&&supportsMedia?<>{section.type==="hero"&&section.media.some(item=>item.media.type==="video")?<HeroPlaybackEditor value={section.playbackMode} onChange={value=>update("playbackMode",value)}/>:null}<MediaEditor section={section} update={update} addMedia={addMedia} youtubeUrl={youtubeUrl} setYoutubeUrl={setYoutubeUrl} addYoutube={addYoutube} assets={assets} onAssetAdded={onAssetAdded}/></>:null}
      {pane==="buttons"&&supportsButtons?<CtaEditor section={section} products={products} pages={pages} update={update}/>:null}
      {pane==="layout"?<div className="page-presentation-editor"><PresentationPicker section={section} update={update}/><label className="page-surface-select">頁面表面<select value={section.theme} onChange={event=>update("theme",event.target.value as PageBuilderSection["theme"])}><option value="warm">暖白精品</option><option value="dark">深色電影感</option><option value="media">媒體暖灰</option></select></label></div>:null}
      {pane==="style"?<BlockVisualStyleEditor section={section} websiteStyle={websiteStyle} update={value=>update("visualStyle",value)}/>:null}
      {pane==="motion"?<MotionEditor section={section} update={update}/>:null}
    </div>
    <footer className="page-section-actions"><div><button type="button" disabled={first} onClick={()=>onMove(-1)}>↑ 往上移</button><button type="button" disabled={last} onClick={()=>onMove(1)}>↓ 往下移</button><button type="button" onClick={onDuplicate}>複製區塊</button></div><div className="danger-zone"><span>危險操作</span><button type="button" onClick={onRemove}>移除區塊</button></div></footer></>:null}
  </article>;
}

function PresentationPicker({section,update}:{section:PageBuilderSection;update:<K extends keyof PageBuilderSection>(key:K,value:PageBuilderSection[K])=>void}) {
  const selected=resolveSectionPresentation(section);
  const mobileSelected=resolveMobileMediaLayout(section);
  const mobileChoices:Array<[PageMobileMediaLayout,string,string]>=[["text-first","文字在上・圖片在下","先閱讀重點，再觀看完整媒體"],["media-first","圖片在上・文字在下","先用圖片吸引目光，再接續文字"],["media-full","圖片滿版・文字接續","讓圖片延伸到手機畫面兩側"],["compact","緊湊圖文","縮短間距，適合精簡內容"]];
  return <><fieldset className="page-presentation-picker"><legend>桌面版面</legend><p>選擇寬螢幕的呈現方式。</p><div>{presentationChoices[section.type].map(([value,label,description,diagram])=><label key={value} className={selected===value?"is-selected":""}><input type="radio" name={`presentation-${section.id}`} value={value} checked={selected===value} onChange={()=>update("presentation",value)}/><span className={`page-layout-diagram is-${diagram}`} aria-hidden="true"><i/><b/><em/></span><strong>{label}</strong><small>{description}</small><span className="page-preset-status">{selected===value?"已選擇":"選擇版型"}</span></label>)}</div></fieldset>{section.type==="mediaText"?<fieldset className="page-mobile-layout-picker"><legend>手機版面</legend><p>手機可以獨立安排圖片與文字順序，不會改變桌面版面。</p><div>{mobileChoices.map(([value,label,description])=><button type="button" key={value} className={mobileSelected===value?"is-selected":""} aria-pressed={mobileSelected===value} onClick={()=>update("mobileMediaLayout",value)}><span className={`mobile-layout-diagram is-${value}`} aria-hidden="true"><i/><b/></span><strong>{mobileSelected===value?"✓ ":""}{label}</strong><small>{description}</small></button>)}</div></fieldset>:null}</>;
}

function CtaEditor({section,products,pages,update}:{section:PageBuilderSection;products:CmsLinkProduct[];pages:PublishedCmsPage[];update:<K extends keyof PageBuilderSection>(key:K,value:PageBuilderSection[K])=>void}) { const set=(index:number,value:typeof section.ctas[number])=>update("ctas",section.ctas.map((item,i)=>i===index?value:item)); return <section className="page-subeditor"><header><div><h3>行動按鈕</h3><p>建議 1–2 個，最多 4 個。</p></div><button type="button" disabled={section.ctas.length>=4} onClick={()=>update("ctas",[...section.ctas,{id:newBuilderId("cta"),enabled:true,label:"新按鈕",stylePreset:"primary",link:{type:"none"}}])}>＋新增按鈕</button></header>{section.ctas.map((cta,index)=><article key={cta.id} className={`owner-surface ${cta.enabled?"is-visible":"is-hidden"}`}><div className="subeditor-heading"><strong>按鈕 {String(index+1).padStart(2,"0")}</strong><Visibility enabled={cta.enabled} onChange={enabled=>set(index,{...cta,enabled})}/></div><div className="cms-grid two"><label>按鈕文字<input value={cta.label} maxLength={80} onChange={event=>set(index,{...cta,label:event.target.value})}/></label><label>按鈕樣式<select value={cta.stylePreset} onChange={event=>set(index,{...cta,stylePreset:event.target.value as typeof cta.stylePreset})}><option value="primary">主要按鈕</option><option value="secondary">次要按鈕</option><option value="text">文字連結</option></select></label></div><SmartLinkPicker editorId={`page-${section.id}-cta-${cta.id}`} label={`按鈕 ${index+1}`} buttonText={cta.label} value={cta.link} products={products} pages={pages} onChange={link=>set(index,{...cta,link})}/><div className="subeditor-actions"><button type="button" disabled={index===0} onClick={()=>update("ctas",move(section.ctas,index,-1))}>↑ 往上</button><button type="button" disabled={index===section.ctas.length-1} onClick={()=>update("ctas",move(section.ctas,index,1))}>↓ 往下</button><button type="button" onClick={()=>update("ctas",[...section.ctas.slice(0,index+1),{...structuredClone(cta),id:newBuilderId("cta")},...section.ctas.slice(index+1)])} disabled={section.ctas.length>=4}>複製</button></div><div className="danger-zone"><span>危險操作</span><button type="button" onClick={()=>confirm("確定移除這個按鈕？")&&update("ctas",section.ctas.filter((_,i)=>i!==index))}>移除按鈕</button></div></article>)}</section>; }

function MediaEditor({section,update,addMedia,youtubeUrl,setYoutubeUrl,addYoutube,assets,onAssetAdded}:{section:PageBuilderSection;update:<K extends keyof PageBuilderSection>(key:K,value:PageBuilderSection[K])=>void;addMedia:(media:MediaAsset)=>void;youtubeUrl:string;setYoutubeUrl:(value:string)=>void;addYoutube:()=>void;assets:AssetRecord[];onAssetAdded:(asset:AssetRecord)=>void}) {
  const [pickerFor,setPickerFor]=useState<number|"new"|null>(null);
  const set=(index:number,value:typeof section.media[number])=>update("media",section.media.map((item,i)=>i===index?value:item));
  async function uploadImage(file:File) {
    const form=new FormData();form.append("file",file);
    const response=await fetch("/api/admin/pages/images",{method:"POST",body:form});
    const data=await response.json() as {error?:string;asset?:AssetRecord;media?:MediaAsset};
    if(!response.ok||!data.asset||!data.media)throw new Error(data.error||"圖片上傳失敗。");
    onAssetAdded(data.asset);return data.media;
  }
  function chooseAsset(asset:AssetRecord){const media=localImageMedia(asset.path);if(pickerFor==="new")addMedia(media);else if(typeof pickerFor==="number")set(pickerFor,{...section.media[pickerFor],media,alt:section.media[pickerFor].alt||asset.alt});setPickerFor(null);}
  return <section className="page-subeditor page-media-editor"><header><div><h3>媒體收藏</h3><p>可混合圖片、影片與 YouTube。移除只會解除本頁引用，不會刪除素材庫檔案。</p></div></header>
    {section.media.map((item,index)=><article key={item.id} className={`owner-surface page-media-card ${item.enabled?"is-visible":"is-hidden"}`}><div className="subeditor-heading"><strong>媒體 {String(index+1).padStart(2,"0")}・{item.media.type==="image"?"圖片":item.media.type==="video"?"影片":"YouTube"}</strong><Visibility enabled={item.enabled} onChange={enabled=>set(index,{...item,enabled})}/></div><MediaUploader label="媒體預覽與替換" value={item.media} usage={section.type==="hero"?"hero":"content"} onImageUpload={uploadImage} imageActionLabel="上傳圖片替換" onChange={media=>set(index,{...item,media})}/><button type="button" className="cms-secondary-button page-library-button" onClick={()=>setPickerFor(index)}>從素材庫替換圖片</button><div className="cms-grid two"><label>替代文字<input value={item.alt} maxLength={240} onChange={event=>set(index,{...item,alt:event.target.value})}/></label><label>標題（選填）<input value={item.title||""} maxLength={180} onChange={event=>set(index,{...item,title:event.target.value})}/></label></div><div className="subeditor-actions"><button type="button" disabled={index===0} onClick={()=>update("media",move(section.media,index,-1))}>↑ 往上</button><button type="button" disabled={index===section.media.length-1} onClick={()=>update("media",move(section.media,index,1))}>↓ 往下</button></div><div className="danger-zone"><span>只解除頁面引用</span><button type="button" onClick={()=>confirm("確定從此區塊移除？素材庫原檔不會被刪除。")&&update("media",section.media.filter((_,i)=>i!==index))}>移除媒體</button></div></article>)}
    <div className="media-add-panel"><div className="page-image-actions"><button type="button" className="cms-secondary-button" onClick={()=>setPickerFor("new")}>從素材庫選圖片</button><MediaUploader label="上傳新圖片或影片" usage={section.type==="hero"?"hero":"content"} showPreview={false} onImageUpload={uploadImage} imageActionLabel="上傳新圖片" videoActionLabel="上傳影片" onChange={addMedia}/></div><div className="youtube-add"><label>YouTube 影片網址<input value={youtubeUrl} onChange={event=>setYoutubeUrl(event.target.value)}/></label><button type="button" onClick={addYoutube} disabled={!youtubeUrl.trim()}>＋新增 YouTube</button></div></div>
    {pickerFor!==null?<ImageLibraryPicker assets={assets} onChoose={chooseAsset} onClose={()=>setPickerFor(null)}/>:null}
  </section>;
}

function ImageLibraryPicker({assets,onChoose,onClose}:{assets:AssetRecord[];onChoose:(asset:AssetRecord)=>void;onClose:()=>void}) {
  const [query,setQuery]=useState("");
  const images=useMemo(()=>assets.filter(asset=>/\.(avif|gif|jpe?g|png|svg|webp)(?:\?|$)/i.test(asset.path)&&`${asset.name} ${asset.category} ${asset.alt}`.toLowerCase().includes(query.trim().toLowerCase())),[assets,query]);
  return <div className="page-asset-picker" role="dialog" aria-modal="true" aria-label="從素材庫選擇圖片"><header><div><h3>從素材庫選擇圖片</h3><p>選取既有圖片，不會建立重複檔案。</p></div><button type="button" onClick={onClose} aria-label="關閉素材庫">×</button></header><label>搜尋素材<input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="名稱、分類或替代文字"/></label><div className="page-asset-grid">{images.map(asset=><button type="button" key={asset.id} onClick={()=>onChoose(asset)}><span><img src={asset.path} alt={asset.alt||asset.name} loading="lazy"/></span><b>{asset.name}</b><small>{asset.alt||"網站圖片"}</small></button>)}{!images.length?<p>找不到符合的圖片。</p>:null}</div></div>;
}

function FeatureEditor({section,update}:{section:PageBuilderSection;update:<K extends keyof PageBuilderSection>(key:K,value:PageBuilderSection[K])=>void}) { const set=(index:number,value:typeof section.items[number])=>update("items",section.items.map((item,i)=>i===index?value:item)); return <section className="page-subeditor"><header><div><h3>特色項目</h3><p>使用精簡卡片整理活動或服務重點。</p></div><button type="button" onClick={()=>update("items",[...section.items,{id:newBuilderId("item"),enabled:true,title:"新特色",body:""}])}>＋新增項目</button></header>{section.items.map((item,index)=><article key={item.id} className={`owner-surface ${item.enabled?"is-visible":"is-hidden"}`}><div className="subeditor-heading"><strong>特色 {index+1}</strong><Visibility enabled={item.enabled} onChange={enabled=>set(index,{...item,enabled})}/></div><label>標題<input value={item.title} onChange={event=>set(index,{...item,title:event.target.value})}/></label><label>內容<textarea value={item.body} onChange={event=>set(index,{...item,body:event.target.value})}/></label><div className="subeditor-actions"><button type="button" disabled={index===0} onClick={()=>update("items",move(section.items,index,-1))}>↑ 往上</button><button type="button" disabled={index===section.items.length-1} onClick={()=>update("items",move(section.items,index,1))}>↓ 往下</button></div><div className="danger-zone"><span>危險操作</span><button type="button" onClick={()=>confirm("確定移除這個項目？")&&update("items",section.items.filter((_,i)=>i!==index))}>移除項目</button></div></article>)}</section>; }

function ProductEditor({section,products,update}:{section:PageBuilderSection;products:CmsLinkProduct[];update:<K extends keyof PageBuilderSection>(key:K,value:PageBuilderSection[K])=>void}) { const available=products.filter(product=>!section.products.some(item=>item.productSlug===product.slug)); const set=(index:number,value:typeof section.products[number])=>update("products",section.products.map((item,i)=>i===index?value:item)); return <section className="page-subeditor"><header><div><h3>商品推薦</h3><p>直接引用正式商品資料，最多 6 款。</p></div><label className="inline-add">新增商品<select value="" disabled={section.products.length>=6} onChange={event=>event.target.value&&update("products",[...section.products,{id:newBuilderId("product"),enabled:true,productSlug:event.target.value}])}><option value="">選擇作品…</option>{available.map(product=><option key={product.slug} value={product.slug}>{product.name}</option>)}</select></label></header>{section.products.map((item,index)=>{const product=products.find(value=>value.slug===item.productSlug);return <article key={item.id} className={`owner-surface ${item.enabled?"is-visible":"is-hidden"}`}><div className="subeditor-heading"><strong>{product?.name||"已失效的商品"}</strong><Visibility enabled={item.enabled} onChange={enabled=>set(index,{...item,enabled})}/></div>{!product?<details><summary>查看技術資訊</summary><code>{item.productSlug}</code></details>:null}<div className="subeditor-actions"><button type="button" disabled={index===0} onClick={()=>update("products",move(section.products,index,-1))}>↑ 往上</button><button type="button" disabled={index===section.products.length-1} onClick={()=>update("products",move(section.products,index,1))}>↓ 往下</button></div><div className="danger-zone"><span>危險操作</span><button type="button" onClick={()=>update("products",section.products.filter((_,i)=>i!==index))}>移除商品</button></div></article>})}</section>; }

function MotionEditor({section,update}:{section:PageBuilderSection;update:<K extends keyof PageBuilderSection>(key:K,value:PageBuilderSection[K])=>void}) {
  const motion=section.motion;
  const set=(patch:Partial<typeof motion>)=>update("motion",{...motion,...patch});
  const presets:Array<[typeof motion.preset,string,string]>=[["none","無動畫","內容直接顯示"],["fade","淡入","安靜地浮現"],["fade-up","淡入上升","向上輕柔帶入"],["slide-left","從左滑入","由左側進入畫面"],["slide-right","從右滑入","由右側進入畫面"],["scale-reveal","縮放揭示","由小至大顯現"],["editorial","編輯式揭示","文字與內容依序出現"]];
  const choices=<T extends number>(label:string,value:number,items:Array<[T,string,string?]>,apply:(next:T)=>void)=><div className="motion-choice"><strong>{label}</strong><div role="group" aria-label={label}>{items.map(([next,name,description])=><button type="button" key={next} className={value===next?"is-selected":""} aria-pressed={value===next} onClick={()=>apply(next)}><span>{value===next?"✓ ":""}{name}</span>{description?<small>{description}</small>:null}</button>)}</div></div>;
  return <section className="page-motion-editor"><header><h3>動畫設定</h3><p>用容易理解的節奏選項調整區塊進場感覺。</p></header><Visibility enabled={motion.enabled} label="開啟動畫" onChange={enabled=>set({enabled})}/>{motion.enabled?<><div className="motion-choice"><strong>動畫方式</strong><div role="group" aria-label="動畫方式">{presets.map(([value,name,description])=><button type="button" key={value} className={motion.preset===value?"is-selected":""} aria-pressed={motion.preset===value} onClick={()=>set({preset:value})}><span>{motion.preset===value?"✓ ":""}{name}</span><small>{description}</small></button>)}</div></div>{choices("出現速度",motion.durationMs,[[1200,"柔和"],[800,"標準"],[500,"明快"]],durationMs=>set({durationMs}))}{choices("開始時機",motion.delayMs,[[0,"立即"],[400,"稍後"],[800,"慢慢出現"]],delayMs=>set({delayMs}))}{choices("移動感",motion.distancePx,[[10,"輕柔"],[18,"清楚"],[36,"強烈"]],distancePx=>set({distancePx}))}{choices("項目節奏",motion.staggerMs,[[60,"緊湊"],[100,"標準"],[180,"寬鬆"]],staggerMs=>set({staggerMs}))}</>:null}</section>;
}
