"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { PageRecord, PageStore } from "@/lib/pageBuilder";
import { resolveCmsLink, type PublishedCmsPage } from "@/lib/cmsLinks";

const statusLabel = { draft: "草稿", published: "已發布", unpublished: "未發布" } as const;
export default function PageListManager() {
  const [store,setStore] = useState<PageStore | null>(null); const [publishedPages,setPublishedPages] = useState<PublishedCmsPage[]>([]); const [message,setMessage] = useState(""); const [creating,setCreating] = useState(false); const [title,setTitle] = useState("");
  async function load() { const response = await fetch("/api/admin/pages", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "讀取失敗"); setStore(data.store); setPublishedPages(data.publishedPages || []); }
  useEffect(() => { void fetch("/api/admin/pages", { cache: "no-store" }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "讀取失敗"); setStore(data.store); setPublishedPages(data.publishedPages || []); }).catch((error) => setMessage(error.message)); }, []);
  async function create() { if (!title.trim() || !store) return; setMessage("建立中…"); const response = await fetch("/api/admin/pages", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ title, version:store.version }) }); const data=await response.json(); if (!response.ok) { setMessage(data.error); return; } location.href=`/admin/pages/${data.page.id}`; }
  async function duplicate(page: PageRecord) { if (!store) return; const response = await fetch("/api/admin/pages", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ sourceId:page.id, version:store.version }) }); const data=await response.json(); if (!response.ok) return setMessage(data.error); location.href=`/admin/pages/${data.page.id}`; }
  async function remove(page: PageRecord, force=false) { if (!store || (!force && !confirm(`確定要刪除「${page.draft.title}」？此操作無法復原。`))) return; const response=await fetch(`/api/admin/pages/${page.id}?version=${store.version}&force=${force}`,{method:"DELETE"}); const data=await response.json(); if (response.status===409 && data.warning) { if (confirm(`${data.warning}\n\n仍要刪除嗎？`)) return remove(page,true); return; } if (!response.ok) return setMessage(data.error); await load(); }
  return <section className="page-admin-shell"><header className="page-admin-heading"><div><p className="eyebrow dark">網站內容管理</p><h1>頁面管理</h1><p>建立、預覽與發布活動／專題頁面；公開網址由系統管理。</p></div><button type="button" className="cms-primary-button" onClick={()=>setCreating(true)}>＋新增頁面</button></header>
    {message ? <p className="cms-feedback" role="status">{message}</p> : null}
    {creating ? <div className="page-create-panel"><h2>新增頁面</h2><label>頁面名稱<input autoFocus value={title} onChange={event=>setTitle(event.target.value)} placeholder="例如：2026 中秋限定禮盒" maxLength={120}/></label><label>頁面類型<select disabled value="campaign"><option value="campaign">活動／專題頁</option></select></label><div><button className="cms-secondary-button" type="button" onClick={()=>setCreating(false)}>取消</button><button className="cms-primary-button" type="button" onClick={create} disabled={!title.trim()}>建立頁面</button></div></div> : null}
    <div className="page-admin-list">{store?.pages.map(page=>{const destination=resolveCmsLink({type:"page",target:page.id},{pages:publishedPages});const publicHref=page.status==="published"&&Boolean(page.publishedSnapshot)&&destination.valid?destination.href:undefined;return <article className={`page-admin-row status-${page.status}`} key={page.id}><div className="page-admin-row-copy"><div><span className={`owner-status status-${page.status}`}>{statusLabel[page.status]}</span><span className="page-block-count">{page.draft.sections.length} 個區塊</span></div><h2>{page.draft.title}</h2><small>最後修改：{new Intl.DateTimeFormat("zh-TW",{dateStyle:"medium",timeStyle:"short"}).format(new Date(page.updatedAt))}</small></div><div className="page-admin-actions"><Link className="is-primary" href={`/admin/pages/${page.id}`}>編輯頁面</Link><Link href={`/admin/pages/${page.id}/preview`} target="_blank" rel="noreferrer">預覽草稿</Link>{publicHref?<Link className="is-public" href={publicHref} target="_blank" rel="noreferrer">查看正式頁 ↗</Link>:null}<details><summary>更多操作</summary><div><button type="button" onClick={()=>duplicate(page)}>複製頁面</button><button type="button" className="danger" onClick={()=>remove(page)}>刪除頁面</button></div></details></div></article>})}{store && !store.pages.length ? <div className="page-admin-empty"><strong>目前還沒有活動／專題頁面</strong><span>按「＋新增頁面」建立第一個草稿。</span></div> : null}</div>
  </section>;
}
