"use client";
import { useMemo, useState } from "react";
type Row={productId:string;productSlug:string;productName:string;skuId:string;skuLabel:string;price:number;pvEnabled:boolean;pvValue:number;active:boolean};
export default function PvManagement({initialRows}:{initialRows:Row[]}){
 const [rows,setRows]=useState(initialRows),[baseline,setBaseline]=useState(initialRows),[query,setQuery]=useState(""),[missingOnly,setMissingOnly]=useState(false),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const visible=useMemo(()=>rows.filter((row)=>(!query||`${row.productName} ${row.skuLabel} ${row.skuId}`.toLowerCase().includes(query.toLowerCase()))&&(!missingOnly||row.active&&!row.pvEnabled)),[rows,query,missingOnly]);
 const patch=(skuId:string,next:Partial<Row>)=>setRows((current)=>current.map((row)=>row.skuId===skuId?{...row,...next}:row));
 async function save(){setSaving(true);setMessage("");try{const changes=[];for(const productId of new Set(rows.map((row)=>row.productId))){const current=rows.filter((row)=>row.productId===productId),before=baseline.filter((row)=>row.productId===productId);const skuOperations=current.flatMap((row)=>{const old=before.find((item)=>item.skuId===row.skuId);if(!old)return[];const fields=[];if(old.pvEnabled!==row.pvEnabled)fields.push({field:"pvEnabled",expectedValue:old.pvEnabled,nextValue:row.pvEnabled});if(old.pvValue!==row.pvValue)fields.push({field:"pvValue",expectedValue:old.pvValue,nextValue:row.pvValue});return fields.length?[{operation:"updateSku",skuId:row.skuId,fields}]:[];});if(skuOperations.length)changes.push({operation:"updateProduct",id:productId,slug:current[0].productSlug,fields:[],skuOperations});}if(!changes.length){setMessage("沒有需要儲存的修改");return;}const response=await fetch("/api/admin/products",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({scope:"productChanges",changes})}),result=await response.json();if(!response.ok)throw new Error(result.error||"儲存失敗");setBaseline(structuredClone(rows));setMessage("PV 設定已儲存；商品管理頁使用同一份 SKU 資料。");}catch(error){setMessage(error instanceof Error?error.message:"儲存失敗");}finally{setSaving(false);}}
 return <div className="membership-rules-manager"><header className="membership-rules-header"><div><p className="eyebrow dark">PV MANAGEMENT</p><h1>SKU PV 管理</h1><p>PV 是商品獎勵計算單位，不是售價、貨幣或投資單位。</p></div><div className="membership-save-box"><button type="button" disabled={saving} onClick={()=>void save()}>{saving?"儲存中…":"儲存 PV 設定"}</button></div></header>{message&&<p className="membership-save-feedback">{message}</p>}<section className="membership-rule-card"><div className="membership-fields two"><label>搜尋商品或規格<input value={query} onChange={(event)=>setQuery(event.target.value)}/></label><label className="membership-switch"><input type="checkbox" checked={missingOnly} onChange={(event)=>setMissingOnly(event.target.checked)}/><span><b>只顯示尚未設定 PV</b></span></label></div><div className="member-credit-history">{visible.map((row)=><article key={row.skuId}><div><strong>{row.productName}</strong><small>{row.skuLabel}・{row.skuId}・售價 NT$ {row.price}</small></div><div><label><input type="checkbox" checked={row.pvEnabled} onChange={(event)=>patch(row.skuId,{pvEnabled:event.target.checked})}/> 啟用 PV</label><label>PV <input type="number" min={0} step="any" value={row.pvValue} onChange={(event)=>patch(row.skuId,{pvValue:Number(event.target.value)})}/></label></div></article>)}</div></section></div>;
}
