import { randomBytes } from "node:crypto";
import assert from "node:assert/strict";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { mock } from "node:test";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";

const root = await fs.mkdtemp(path.join(os.tmpdir(), "kd-credit-integration-"));
process.env.KD_DATA_DIR = root;
delete process.env.RAILWAY_VOLUME_MOUNT_PATH;
process.env.AUTH_SESSION_SECRET = randomBytes(32).toString("hex");
process.env.MEMBER_IDENTITY_SECRET = process.env.AUTH_SESSION_SECRET;
// No test can contact an external notification service.
globalThis.fetch = async () => { throw new Error("External network forbidden in isolated test"); };
const globals = globalThis as typeof globalThis & { __creditTestCookie?: string; __creditTestAdminCookie?: string };
let checks = 0;
function check(name: string, body: () => unknown) { body(); checks++; console.log(`PASS ${checks} ${name}`); }
const commerce = await import("../lib/membershipCommerce");
const rulesModule = await import("../lib/membershipBusinessRules");
const policies = await import("../lib/membershipPolicies");
const identity = await import("../lib/memberIdentity");
const auth = await import("../lib/memberAuth");
const storage = await import("../lib/storagePaths");
const copy = await import("../lib/memberCenterCopy");
const copyStore = await import("../lib/memberCenterCopyStore");
const serverCopy = await import("../lib/creditDisplayCopy");
const { applyOrderCredit } = await import("../lib/orderCredit");
const scheduler = await import("../lib/subscriptionOrderScheduler");
const { projectOrderFinancialBreakdown } = await import("../lib/orderFinancialProjection");
const { cancelOrderCanonically } = await import("../lib/orderCancellation");
const { POST } = await import("../app/api/orders/route");
const { PATCH } = await import("../app/api/member/subscription/route");
const { PATCH: adminStatusApi } = await import("../app/api/admin/orders/[orderNumber]/route");
const adminAuth = await import("../lib/adminAuth");
const { GET: quoteApi } = await import("../app/api/member/credit/quote/route");
const { GET: operationalApi } = await import("../app/api/commerce/operational-rules/route");
const { default: Provider, MemberCopyText } = await import("../components/member/MemberCenterCopyProvider");
const { default: AdminCopy } = await import("../components/admin/MemberCenterCopyManager");
const { default: PreferenceFields } = await import("../components/member/CreditPreferenceFields");
const { default: Help } = await import("../components/member/CreditHelpDialog");

const now = new Date("2026-10-06T03:00:00.000Z");
const rulesFile = storage.getMembershipRulesFile();
const stateFile = storage.getMembershipCommerceStateFile();
const websiteFile = storage.getWebsiteDataFile();
const orderDir = storage.getOrdersDir();
const readOrder = async (number: string) => JSON.parse(await fs.readFile(path.join(orderDir, `${number}.json`), "utf8"));
const writeOrder = async (order: Record<string, unknown>) => fs.writeFile(path.join(orderDir, `${order.orderNumber}.json`), JSON.stringify(order));
const website = { version: 1, menu: { products: [{ slug: "test-coffee", name: "Test Coffee", active: true, purchasable: true, status: "active", stock: 100, skus: [{ id: "test-half", label: "半磅咖啡豆", detail: "227g", kind: "beans", price: 1000, stock: 100, enabled: true }] }] } };
const rules = structuredClone(rulesModule.DEFAULT_MEMBERSHIP_RULES);
rules.credit.maximumOrderPercent = 70;
rules.credit.redemption = { mode: "minimum-payable", amount: 100 };
rules.credit.allowZeroTotal = false;
rules.subscription.discountPercent = 95;
rules.shipping.homeDeliveryShippingFee = 100;
rules.shipping.homeDeliveryCodFee = 50;
rules.shipping.subscriptionShippingDiscount = 60;
const overrides = { [copy.CREDIT_NAME_KEY]: "測試咖啡金", "member.dashboard.label.3dd941956d": "KD弊", "member.dashboard.label.622f3c5acb": "枚" };

try {
  await fs.mkdir(path.dirname(websiteFile), { recursive: true });
  await fs.mkdir(orderDir, { recursive: true });
  await fs.mkdir(storage.getMembersDir(), { recursive: true });
  await fs.writeFile(websiteFile, JSON.stringify(website));
  await rulesModule.saveMembershipBusinessRules({ expectedRevision: 0, rules, now }, rulesFile);
  await copyStore.saveMemberCenterCopy({ expectedRevision: 0, overrides });
  const canonical = await identity.provisionCanonicalMember({ provider: "email", subject: "credit-test@example.test", persistMember: async () => undefined });
  const memberId = canonical.member.memberId;
  await fs.writeFile(path.join(storage.getMembersDir(), `${memberId}.json`), JSON.stringify({ id: memberId, memberNumber: canonical.member.memberNumber, displayName: "Isolated Member", email: "credit-test@example.test", loginEmail: "credit-test@example.test", phone: "0912345678", createdAt: now.toISOString(), updatedAt: now.toISOString() }));
  globals.__creditTestCookie = auth.createSessionToken(memberId);
  const grant = async (amount: number, key: string) => commerce.issueCredit({ memberId, amount, sourceType: "manual", sourceReference: key, idempotencyKey: key, now });
  await grant(4000, "initial-balance");
  const max = (merchandiseSubtotal: number, shipping: number, value = rules) => policies.maximumCreditRedemption({ merchandiseSubtotal, shipping, rules: value });
  check("70% cap excludes shipping and rounds down", () => { assert.equal(max(1000, 100), 700); assert.equal(max(101, 100), 70); });
  check("minimum payable combines independently", () => { const value = structuredClone(rules); value.credit.redemption = { mode: "minimum-payable", amount: 500 }; assert.equal(max(1000, 0, value), 500); });
  check("fixed and legacy percentage combine", () => { const value = structuredClone(rules); value.credit.redemption = { mode: "maximum-fixed", amount: 200 }; assert.equal(max(1000, 100, value), 200); value.credit.redemption = { mode: "maximum-percentage", percent: 20 }; assert.equal(max(1000, 100, value), 200); });
  check("zero/one-cent and legacy default", () => { const value = structuredClone(rules); value.credit.redemption = { mode: "unlimited" }; delete value.credit.maximumOrderPercent; assert.equal(max(1000, 0, value), 700); assert.equal(max(0, 100, value), 0); assert.equal(max(1, 0, value), 0); });
  check("independent cap can be disabled while preserving old restrictions", () => { const value = structuredClone(rules); value.credit.maximumOrderPercentEnabled = false; assert.equal(max(1000, 100, value), 1000); value.credit.appliesToShipping = "no"; assert.equal(max(1000, 100, value), 900); });
  check("new default enabled at 70, legacy reads never enable it", () => { assert.equal(rulesModule.DEFAULT_MEMBERSHIP_RULES.credit.maximumOrderPercentEnabled, true); const old = structuredClone(rules); delete old.credit.maximumOrderPercentEnabled; const normalized = rulesModule.validateMembershipBusinessRules(old); assert.equal(normalized.credit.maximumOrderPercentEnabled, false); assert.equal(max(1000, 0, normalized), 900); });
  const legacyFile = path.join(root, "legacy-rules.json");
  const legacyStore = JSON.parse(await fs.readFile(rulesFile, "utf8"));
  for (const version of legacyStore.versions) delete version.rules.credit.maximumOrderPercentEnabled;
  await fs.writeFile(legacyFile, JSON.stringify(legacyStore));
  const originalLegacy = await fs.readFile(legacyFile, "utf8");
  assert.equal((await rulesModule.readMembershipRulesStore(legacyFile)).versions.at(-1)?.rules.credit.maximumOrderPercentEnabled, false);
  assert.equal(await fs.readFile(legacyFile, "utf8"), originalLegacy); checks++;
  for (const percent of [-1, 101, 70.5, Number.NaN]) check(`invalid cap ${percent}`, () => assert.throws(() => rulesModule.validateMembershipBusinessRules({ ...rules, credit: { ...rules.credit, maximumOrderPercent: percent } })));
  const templates = copy.MEMBER_CENTER_COPY_CATALOG.filter((entry) => entry.tokens.creditName);
  for (const entry of templates) {
    const values = Object.fromEntries(Object.keys(entry.tokens).filter((name) => name !== "creditName").map((name) => [name, name === "percent" ? 70 : "NT$ 120"]));
    check(`shared name ${entry.key}`, () => { assert.equal(copy.memberCopyValidationError(entry.key, entry.defaultText), null); const rendered = copy.resolveMemberCopy(overrides, entry.key, values); assert.ok(rendered.includes("測試咖啡金") || entry.key === "member.dashboard.label.3dd941956d"); assert.ok(!rendered.includes("{creditName}")); });
  }
  check("name + amount + ratio and injected name cannot be overridden by caller", () => { assert.ok(copy.resolveMemberCopy(overrides, "credit.help.policy", { creditName: "wrong", percent: 70 }).includes("70% 測試咖啡金")); assert.ok(copy.resolveMemberCopy(overrides, "credit.notice.amount", { amount: "NT$ 120" }).includes("測試咖啡金 NT$ 120")); });
  const historical = { ...overrides, "member.subscription.label.a519a98b2f": "我的老名字", "member.rewards.description.a2e8013bd2": "{pointName} {pointName2} 換 {creditAmount} 舊抵用金" };
  check("legacy overrides retained verbatim, including required old business tokens", () => { assert.deepEqual(copy.normalizeMemberCopyOverrides(historical), historical); assert.equal(copy.resolveMemberCopy(historical, "member.subscription.label.a519a98b2f"), "我的老名字"); assert.equal(copy.resolveMemberCopy(historical, "member.dashboard.label.3dd941956d"), "KD弊"); assert.equal(copy.resolveMemberDisplayValue(historical, " 元"), " 枚"); assert.ok(copy.memberCopyValidationError("member.rewards.description.a2e8013bd2", "{creditName}")); });
  const render = (child: ReturnType<typeof createElement>) => {
    const props = { initialOverrides: overrides, children: child };
    return renderToStaticMarkup(createElement(Provider, props));
  };
  check("explicit key survives differing fallback text", () => assert.ok(render(createElement(MemberCopyText, { copyKey: "credit.checkout.title", fallback: "changed default sentence" })).includes("測試咖啡金")));
  check("all recurring options use shared name and stay compact", () => { const html = render(createElement(PreferenceFields, { value: { mode: "fixed", amount: 300 }, onChange: () => undefined })); assert.ok(html.includes("每期自動使用最高可抵測試咖啡金金額")); assert.ok(html.includes("每期自動使用指定測試咖啡金金額")); assert.ok(!html.includes("使用說明")); assert.ok(!html.includes("持續至您修改或關閉")); assert.ok(render(createElement(Help)).includes("持續至您修改或關閉")); });
  check("single help modal title and trigger use shared name", () => { const html = render(createElement(Help)); assert.equal((html.match(/<dialog/g) ?? []).length, 1); assert.ok(html.includes("測試咖啡金使用說明")); });
  check("Admin warns and previews independent historical wording", () => { const html = renderToStaticMarkup(createElement(AdminCopy, { initialRevision: 1, initialOverrides: historical })); assert.ok(html.includes("此文案尚未引用統一名稱")); assert.ok(html.includes("KD弊")); assert.ok(html.includes("使用 {creditName} 後的預設模板預覽")); assert.ok(html.includes("可用測試咖啡金")); });
  const beforeHistory = await fs.readFile(stateFile, "utf8");
  const beforeOrders = await fs.readdir(orderDir);
  check("server prompt exact allowlist only", () => assert.equal(copy.creditDisplayName(overrides), "測試咖啡金"));
  assert.equal(await serverCopy.creditSystemMessage("可用抵用金不足"), "可用測試咖啡金不足"); checks++;
  assert.equal(await serverCopy.creditSystemMessage("任意自訂抵用金來源文字"), "任意自訂抵用金來源文字"); checks++;
  await copyStore.saveMemberCenterCopy({ expectedRevision: 1, overrides: { ...overrides, [copy.CREDIT_NAME_KEY]: "第二測試金" } });
  assert.equal(await fs.readFile(stateFile, "utf8"), beforeHistory); assert.deepEqual(await fs.readdir(orderDir), beforeOrders); checks++;
  await copyStore.saveMemberCenterCopy({ expectedRevision: 2, overrides });

  const address = { recipientName: "Test", phone: "0912345678", postalCode: "800", city: "高雄市", district: "新興區", addressLine: "測試路 1 號" };
  const checkoutBody = (orderMode: string, extra = {}) => ({ idempotencyKey: crypto.randomUUID(), orderMode, customer: { name: "測試", phone: "0912345678", email: "credit-test@example.test" }, items: [{ slug: "test-coffee", optionId: "test-half", optionLabel: "半磅咖啡豆", quotedUnitPrice: 1000, quantity: 1, preparationLabel: "咖啡豆" }], store: orderMode === "711_cod" ? { id: "123456", name: "Test Store", address: "Test address" } : null, deliveryAddress: orderMode === "home_delivery" ? address : null, paymentMethod: orderMode === "home_delivery" ? "cash_on_delivery" : null, studioPickup: orderMode === "studio_pickup" ? { preferredDate: "2026-10-20", preferredTime: "14:00" } : null, requestedCredit: 999999, ...extra });
  const post = async (body: object) => { const response = await POST(new Request("http://localhost/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) })); const result = await response.json(); assert.equal(response.status, 200, JSON.stringify(result)); return result; };
  const initial = checkoutBody("home_delivery", { subscriptionIntent: { consent: true, intervalDays: 30, creditPreference: { mode: "maximum" } } });
  const first = await post(initial);
  const firstOrder = await readOrder(first.orderNumber);
  check("first subscription order has real reservation, server cap and excludes COD", () => { assert.equal(first.credit.appliedAmount, 700); assert.equal(firstOrder.total, 450); assert.equal(projectOrderFinancialBreakdown(firstOrder).creditApplied, 700); });
  const balanceBeforeReplay = await commerce.getAvailableCredit(memberId, now);
  const stockBeforeReplay = await fs.readFile(websiteFile, "utf8");
  await post(initial);
  check("checkout replay does not reserve or decrement inventory again", () => assert.equal(firstOrder.credit.reservationId, first.credit.reservationId));
  assert.equal(await commerce.getAvailableCredit(memberId, now), balanceBeforeReplay); assert.equal(await fs.readFile(websiteFile, "utf8"), stockBeforeReplay); checks++;
  const firstBalanceBeforeName = await commerce.getAvailableCredit(memberId, now);
  await copyStore.saveMemberCenterCopy({ expectedRevision: 3, overrides: { ...overrides, [copy.CREDIT_NAME_KEY]: "第二測試金" } });
  await post(initial);
  assert.equal(await commerce.getAvailableCredit(memberId, now), firstBalanceBeforeName); assert.equal((await readOrder(first.orderNumber)).credit.appliedAmount, 700); checks++;
  await copyStore.saveMemberCenterCopy({ expectedRevision: 4, overrides });
  const quoteResponse = await quoteApi(new Request("http://localhost/api/member/credit/quote?subtotal=1000&shipping=100"));
  assert.equal((await quoteResponse.json()).maximumUsable, 700); checks++;
  const policyResponse = await operationalApi(); assert.equal((await policyResponse.json()).credit.maximumOrderPercent, 70); checks++;
  const general = await post(checkoutBody("711_cod")); assert.equal(general.credit.appliedAmount, 700); checks++;
  const studio = await post(checkoutBody("studio_pickup")); assert.equal(studio.credit.appliedAmount, 700); checks++;
  globals.__creditTestAdminCookie = adminAuth.createAdminSessionValue();
  await writeOrder({ ...(await readOrder(studio.orderNumber)), status: "ready_for_pickup" });
  const adminComplete = await adminStatusApi(new Request("http://localhost/api/admin/orders/status", { method: "PATCH", body: JSON.stringify({ status: "completed" }) }), { params: Promise.resolve({ orderNumber: studio.orderNumber }) });
  assert.equal(adminComplete.status, 200, JSON.stringify(await adminComplete.json()));
  const adminReplay = await adminStatusApi(new Request("http://localhost/api/admin/orders/status", { method: "PATCH", body: JSON.stringify({ status: "completed" }) }), { params: Promise.resolve({ orderNumber: studio.orderNumber }) });
  assert.equal(adminReplay.status, 200); assert.equal((await commerce.getSafeOrderCreditReservation({ orderId: studio.orderNumber, memberId }))?.status, "consumed"); checks++;
  const bad = await POST(new Request("http://localhost/api/orders", { method: "POST", body: JSON.stringify(checkoutBody("711_cod", { requestedCredit: -1 })) }));
  assert.ok((await bad.json()).error.includes("測試咖啡金")); checks++;
  let state = await commerce.readMembershipCommerceState();
  let subscription = Object.values(state.subscriptions).find((item) => item.startedFromOrderId === first.orderNumber)!;
  check("initial enrollment persists maximum choice", () => assert.deepEqual(subscription.creditPreference, { mode: "maximum" }));
  await commerce.activateSubscriptionFromPickup({ subscriptionId: subscription.subscriptionId, orderId: first.orderNumber, idempotencyKey: "activate-test", now });
  const makeCycle = async (sequence: number, kind: "scheduled" | "manual_replenishment" = "scheduled") => commerce.generateSubscriptionCycle({ subscriptionId: subscription.subscriptionId, sequence, plannedDate: "2026-10-12", kind, idempotencyKey: `cycle-${sequence}`, now });
  const cycle = await makeCycle(101);
  await commerce.lockSubscriptionCycle({ cycleId: cycle.cycleId, idempotencyKey: "lock-max", now });
  state = await commerce.readMembershipCommerceState(); subscription = state.subscriptions[subscription.subscriptionId];
  await commerce.updateSubscriptionPreferences({ memberId, subscriptionId: subscription.subscriptionId, expectedRevision: subscription.revision, creditPreference: { mode: "fixed", amount: 300 }, idempotencyKey: "switch-fixed", now });
  let isolatedRuleStore = await rulesModule.readMembershipRulesStore();
  await rulesModule.saveMembershipBusinessRules({ expectedRevision: isolatedRuleStore.revision, rules: { ...rules, credit: { ...rules.credit, maximumOrderPercent: 10 } }, now });
  const renewal = await scheduler.runSubscriptionOrderScheduler({ today: "2026-10-10", now });
  assert.equal(renewal.failed, 0, JSON.stringify(renewal));
  state = await commerce.readMembershipCommerceState();
  const renewalOrder = await readOrder(state.cycles[cycle.cycleId].createdOrderId!);
  check("renewal uses frozen maximum choice and 70% discounted price cap", () => { assert.equal(renewalOrder.credit.appliedAmount, 665); assert.equal(renewalOrder.totalBeforeCredit, 1040); assert.equal(renewalOrder.total, 375); assert.equal(state.cycles[cycle.cycleId].pricingSnapshot?.creditReserved, 665); });
  isolatedRuleStore = await rulesModule.readMembershipRulesStore();
  await rulesModule.saveMembershipBusinessRules({ expectedRevision: isolatedRuleStore.revision, rules, now });
  const reservationsBeforeSchedulerReplay = Object.keys(state.creditReservations).length;
  await scheduler.runSubscriptionOrderScheduler({ today: "2026-10-10", now });
  assert.equal((await commerce.readMembershipCommerceState()).creditReservations[renewalOrder.credit.reservationId].amount, 665); assert.equal(Object.keys((await commerce.readMembershipCommerceState()).creditReservations).length, reservationsBeforeSchedulerReplay); checks++;
  // Fixed mode on a manual replenishment cycle; no anchor/date mutation.
  const anchor = state.subscriptions[subscription.subscriptionId].anchorDate;
  const replenishResponse = await PATCH(new Request("http://localhost/api/member/subscription", { method: "PATCH", headers: { origin: "http://localhost", "Content-Type": "application/json" }, body: JSON.stringify({ action: "replenish", subscriptionId: subscription.subscriptionId, idempotencyKey: "api-manual" }) }));
  assert.equal(replenishResponse.status, 200, JSON.stringify(await replenishResponse.json()));
  const manual = Object.values((await commerce.readMembershipCommerceState()).cycles).find((item) => item.kind === "manual_replenishment")!;
  await scheduler.runSubscriptionOrderScheduler({ today: "2026-10-10", now });
  state = await commerce.readMembershipCommerceState();
  const manualOrder = await readOrder(state.cycles[manual.cycleId].createdOrderId!);
  check("manual replenishment uses fixed preference and preserves anchor", () => { assert.equal(manualOrder.credit.appliedAmount, 300); assert.equal(state.subscriptions[subscription.subscriptionId].anchorDate, anchor); });
  await cancelOrderCanonically({ orderNumber: manualOrder.orderNumber, cancellationReason: "測試取消", cancelledBy: "member", idempotencyKey: "cancel-manual", now: () => now, sendNotification: async () => ({ sent: false }) });
  const balanceAfterCancel = await commerce.getAvailableCredit(memberId, now);
  const websiteAfterCancel = await fs.readFile(websiteFile, "utf8");
  await cancelOrderCanonically({ orderNumber: manualOrder.orderNumber, cancellationReason: "測試取消", cancelledBy: "member", idempotencyKey: "cancel-manual", now: () => now, sendNotification: async () => ({ sent: false }) });
  assert.equal(await commerce.getAvailableCredit(memberId, now), balanceAfterCancel); assert.equal(await fs.readFile(websiteFile, "utf8"), websiteAfterCancel); checks++;
  state = await commerce.readMembershipCommerceState();
  assert.equal(state.creditReservations[manualOrder.credit.reservationId].status, "released"); assert.equal(state.cycles[manual.cycleId].status, "cancelled"); checks++;
  await commerce.settleCreditReservationForOrder({ orderId: renewalOrder.orderNumber, action: "consume", idempotencyKey: "complete-renewal", reason: "測試成功取貨", now });
  await commerce.settleCreditReservationForOrder({ orderId: renewalOrder.orderNumber, action: "consume", idempotencyKey: "complete-renewal", reason: "測試成功取貨", now }); checks++;
  // Simulate interruption after the order/ledger commit but before cycle linking.
  state = await commerce.readMembershipCommerceState();
  for (const recoveredCycle of [manual, cycle]) {
    state.cycles[recoveredCycle.cycleId].status = "locked";
    state.cycles[recoveredCycle.cycleId].createdOrderId = null;
    delete state.idempotency[`cycle:order:scheduler-order:${recoveredCycle.cycleId}`];
  }
  await fs.writeFile(stateFile, JSON.stringify(state));
  await writeOrder({ ...(await readOrder(renewalOrder.orderNumber)), status: "completed" });
  const terminalStock = await fs.readFile(websiteFile, "utf8");
  const terminalBalance = await commerce.getAvailableCredit(memberId, now);
  const terminalRecovery = await scheduler.runSubscriptionOrderScheduler({ today: "2026-10-10", now });
  assert.equal(terminalRecovery.failed, 0, JSON.stringify(terminalRecovery));
  state = await commerce.readMembershipCommerceState();
  assert.equal(state.cycles[manual.cycleId].status, "cancelled");
  assert.equal(state.cycles[cycle.cycleId].status, "completed");
  assert.equal(await commerce.getAvailableCredit(memberId, now), terminalBalance);
  assert.equal(await fs.readFile(websiteFile, "utf8"), terminalStock); checks++;
  const recoveredProgress = await commerce.getGiftProgress(subscription.subscriptionId);
  await scheduler.runSubscriptionOrderScheduler({ today: "2026-10-10", now });
  assert.equal(await commerce.getGiftProgress(subscription.subscriptionId), recoveredProgress); checks++;
  // Request-local API action validates ownership/revision and changes only future preferences.
  state = await commerce.readMembershipCommerceState(); subscription = state.subscriptions[subscription.subscriptionId];
  const response = await PATCH(new Request("http://localhost/api/member/subscription", { method: "PATCH", headers: { "origin": "http://localhost", "Content-Type": "application/json" }, body: JSON.stringify({ action: "change-credit", subscriptionId: subscription.subscriptionId, expectedRevision: subscription.revision, creditPreference: { mode: "off" }, idempotencyKey: "api-off" }) }));
  assert.equal(response.status, 200, JSON.stringify(await response.json())); checks++;
  const offCycle = await makeCycle(103);
  await scheduler.runSubscriptionOrderScheduler({ today: "2026-10-10", now });
  state = await commerce.readMembershipCommerceState();
  const offOrder = await readOrder(state.cycles[offCycle.cycleId].createdOrderId!);
  assert.equal(offOrder.credit.appliedAmount, 0); assert.equal(offOrder.total, 1040); checks++;
  // Different orders compete under the same ledger lock. Maximum spends remaining balance.
  const smallMember = (await identity.provisionCanonicalMember({ provider: "email", subject: "small@example.test", persistMember: async () => undefined })).member.memberId;
  await commerce.issueCredit({ memberId: smallMember, amount: 120, sourceType: "manual", sourceReference: "small", idempotencyKey: "small", now });
  const bare = (orderNumber: string) => ({ orderNumber, member: { memberId: smallMember }, status: "new_order", orderMode: "home_delivery", subtotal: 1000, shipping: 100, codServiceFee: 50, total: 1150, inventoryTransaction: { state: "inventory_committed" } });
  await writeOrder(bare("KD20261006-111111"));
  const fixedLow = await applyOrderCredit({ memberId: smallMember, orderNumber: "KD20261006-111111", preference: { mode: "fixed", amount: 300 }, now });
  assert.equal((fixedLow.credit as { appliedAmount: number }).appliedAmount, 120); assert.equal(await commerce.getAvailableCredit(smallMember, now), 0); checks++;
  await commerce.issueCredit({ memberId: smallMember, amount: 120, sourceType: "manual", sourceReference: "small-2", idempotencyKey: "small-2", now });
  await writeOrder(bare("KD20261006-222222")); await writeOrder(bare("KD20261006-333333"));
  const parallel = await Promise.all(["KD20261006-222222", "KD20261006-333333"].map((orderNumber) => applyOrderCredit({ memberId: smallMember, orderNumber, preference: { mode: "maximum" }, now })));
  assert.equal(parallel.reduce((sum, order) => sum + (order.credit as { appliedAmount: number }).appliedAmount, 0), 120); assert.equal(await commerce.getAvailableCredit(smallMember, now), 0); checks++;
  // Crash simulation: ledger committed, order snapshot absent. Recover existing reservation.
  await commerce.issueCredit({ memberId: smallMember, amount: 500, sourceType: "manual", sourceReference: "recover", idempotencyKey: "recover", now });
  await writeOrder(bare("KD20261006-444444"));
  const interrupted = await commerce.reserveCredit({ memberId: smallMember, orderId: "KD20261006-444444", requestedAmount: 300, merchandiseSubtotal: 1000, shipping: 100, idempotencyKey: "order-credit:KD20261006-444444", now });
  const recovered = await applyOrderCredit({ memberId: smallMember, orderNumber: "KD20261006-444444", requestedAmount: 300, now });
  assert.equal((recovered.credit as { reservationId: string }).reservationId, interrupted.reservationId); assert.equal(await commerce.getAvailableCredit(smallMember, now), 200); checks++;
  // A released write-failure attempt can reserve again with the stable order key.
  await writeOrder(bare("KD20261006-555555"));
  const released = await commerce.reserveCredit({ memberId: smallMember, orderId: "KD20261006-555555", requestedAmount: 100, merchandiseSubtotal: 1000, shipping: 100, idempotencyKey: "order-credit:KD20261006-555555", now });
  await commerce.settleCreditReservation({ reservationId: released.reservationId, action: "release", idempotencyKey: "simulated-write-failed", reason: "測試", now });
  const retried = await applyOrderCredit({ memberId: smallMember, orderNumber: "KD20261006-555555", requestedAmount: 100, now });
  assert.notEqual((retried.credit as { reservationId: string }).reservationId, released.reservationId); assert.equal(await commerce.getAvailableCredit(smallMember, now), 100); checks++;
  await commerce.settleCreditReservationForOrder({ orderId: "KD20261006-555555", action: "consume", idempotencyKey: "retry-consume", reason: "測試", now });
  assert.equal((await commerce.getSafeOrderCreditReservation({ orderId: "KD20261006-555555", memberId: smallMember }))?.status, "consumed"); checks++;
  await writeOrder({ ...bare("KD20261006-666666"), status: "cancelled" });
  await writeOrder({ ...bare("KD20261006-777777"), status: "inventory_pending", inventoryTransaction: { state: "inventory_pending" } });
  const priorTerminal = await fs.readFile(stateFile, "utf8");
  await applyOrderCredit({ memberId: smallMember, orderNumber: "KD20261006-666666", requestedAmount: 100, now });
  await applyOrderCredit({ memberId: smallMember, orderNumber: "KD20261006-777777", requestedAmount: 100, now });
  assert.equal(await fs.readFile(stateFile, "utf8"), priorTerminal); checks++;
  // Actual atomic IO failure after ledger reservation releases and can be retried.
  await writeOrder(bare("KD20261006-888888"));
  const nativeRename = fs.rename.bind(fs);
  const renameMock = mock.method(fs, "rename", async (from: Parameters<typeof fs.rename>[0], to: Parameters<typeof fs.rename>[1]) => {
    if (String(to).endsWith("KD20261006-888888.json")) throw Object.assign(new Error("isolated order write failure"), { code: "EIO" });
    return nativeRename(from, to);
  });
  const beforeIoFailure = await commerce.getAvailableCredit(smallMember, now);
  await assert.rejects(applyOrderCredit({ memberId: smallMember, orderNumber: "KD20261006-888888", requestedAmount: 100, now }));
  renameMock.mock.restore();
  assert.equal(await commerce.getAvailableCredit(smallMember, now), beforeIoFailure); assert.equal((await readOrder("KD20261006-888888")).credit, undefined); checks++;
  const ioRetried = await applyOrderCredit({ memberId: smallMember, orderNumber: "KD20261006-888888", requestedAmount: 100, now });
  assert.equal((ioRetried.credit as { appliedAmount: number }).appliedAmount, 100); checks++;
  await commerce.issueCredit({ memberId: smallMember, amount: 100, sourceType: "manual", sourceReference: "durable", idempotencyKey: "durable", now });
  await writeOrder(bare("KD20261006-999999"));
  const committedRename = mock.method(fs, "rename", async (from: Parameters<typeof fs.rename>[0], to: Parameters<typeof fs.rename>[1]) => {
    await nativeRename(from, to);
    if (String(to).endsWith("KD20261006-999999.json")) throw Object.assign(new Error("IO reported after commit"), { code: "EIO" });
  });
  const durable = await applyOrderCredit({ memberId: smallMember, orderNumber: "KD20261006-999999", requestedAmount: 100, now });
  committedRename.mock.restore();
  const durableCredit = durable.credit as { reservationId: string; appliedAmount: number };
  assert.equal(durableCredit.appliedAmount, 100); assert.equal((await commerce.readMembershipCommerceState()).creditReservations[durableCredit.reservationId].status, "reserved"); assert.equal(await commerce.getAvailableCredit(smallMember, now), 0); checks++;
  const { createMembershipNotificationTemplate } = await import("../lib/memberNotificationAutomation");
  const notice = { notificationId: "template-only", eventType: "credit_issued" as const, memberId, channels: ["member_center" as const], status: "pending" as const, sourceEvent: "test", createdAt: now.toISOString(), safeData: { amount: 120 } };
  const issuedNotice = await createMembershipNotificationTemplate(notice);
  const expiringNotice = await createMembershipNotificationTemplate({ ...notice, eventType: "credit_expiring" });
  assert.ok(issuedNotice.subject.includes("測試咖啡金")); assert.ok(issuedNotice.text.includes("NT$120")); assert.ok(expiringNotice.text.includes("測試咖啡金")); checks++;
  state = await commerce.readMembershipCommerceState();
  const customLabelEntry = Object.values(state.creditEntries).find((entry) => entry.memberId === smallMember)!;
  customLabelEntry.sourceLabel = "Owner 自訂抵用金來源";
  await fs.writeFile(stateFile, JSON.stringify(state));
  const customLabelState = await fs.readFile(stateFile, "utf8");
  const customDashboard = await commerce.getMemberCommerceDashboard(smallMember, now);
  const customLabel = customDashboard.credits.find((entry) => entry.creditEntryId === customLabelEntry.creditEntryId)!;
  assert.equal(customLabel.sourceLabel, "Owner 自訂抵用金來源"); assert.equal(customLabel.sourceCopyKey, undefined);
  assert.equal(await fs.readFile(stateFile, "utf8"), customLabelState); checks++;
  const failureState = await fs.readFile(stateFile, "utf8");
  const failureBalance = await commerce.getAvailableCredit(memberId, now);
  await fs.writeFile(websiteFile, JSON.stringify({ ...website, menu: { products: [{ ...website.menu.products[0], stock: 0, skus: [{ ...website.menu.products[0].skus[0], stock: 0 }] }] } }));
  const failedBody = checkoutBody("home_delivery");
  const failedResponse = await POST(new Request("http://localhost/api/orders", { method: "POST", body: JSON.stringify(failedBody) }));
  assert.notEqual(failedResponse.status, 200); assert.equal(await commerce.getAvailableCredit(memberId, now), failureBalance); assert.equal(await fs.readFile(stateFile, "utf8"), failureState); checks++;
  console.log(`CREDIT SUBSCRIPTION INTEGRATION: ${checks} checks; only isolated ${root}`);
} finally {
  mock.restoreAll();
  delete globals.__creditTestCookie;
  delete globals.__creditTestAdminCookie;
  assert.ok(path.resolve(root).startsWith(path.join(os.tmpdir(), "kd-credit-integration-")));
  await fs.rm(root, { recursive: true, force: true });
}
